services:                                                                        
  arroyo:                                                                        
    image: ghcr.io/arroyosystems/arroyo:latest                                   
    ports:                                                                       
      - "5115:5115"                                                              
    depends_on:                                                                  
      - kafka                                                                    
    networks:                                                                    
      - router_monitor                                                           
                                                                                 
  kafka:                                                                         
    image: apache/kafka:4.1.2                                                    
    ports:                                                                       
      - "9092:9092"                                                              
    networks:                                                                    
      - router_monitor                                                           
                                                                                 
networks:                                                                        
  router_monitor:                                                                
    name: router_monitor
